### ISSUE TITLE
No commented code in class

### ISSUE THREAD

**Issue by white-collar** [ext11/homework29_Polous#8]
https://github.com/ext11/homework29_Polous/blob/86678fdc68a4ec5bd9e3a8c363566f2403b6d1cb/src/test/java/ua/com/alevel/entity/BoardPresenterTest.java#L14

Please, never keep commented code in repository

**Comment by vladikpolous** [comment]
I changed this code [here](https://github.com/ext11/homework29_Polous/pull/14/commits/cc529e0a5aef031e41af689c4050c2c7e5720de4)
